name:                emu-framework
version:             0.1.0.0
description:         Emulator framework in Haskell, targeting NES
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/emu-framewwork.git

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- sdl2
- sdl2-ttf
- text

default-extensions:
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- RecordWildCards
- ScopedTypeVariables
- Strict

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
# Default optimisation is -O == -O1
# And is quicker that -O2 for the gradientCol example

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        emu-framework
